# Default values for openvpn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

updateStrategy:
  type: Recreate

# For supporting pulling from private registries
# imagePullSecretName:

image:
  repository: k4kratik/openvpn
  tag: v1
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  externalPort: 1194
  internalPort: 1194
  # hostPort: 443
  externalIPs: []
  # clusterIP: None
  # LoadBalancerSourceRanges: 0.0.0.0/0
  # loadBalancerIP: 10.0.0.1

  ## Here annotations can be added to the openvpn service
  # annotations:
  #   external-dns.alpha.kubernetes.io/hostname: vpn.example.com
  # annotations needed for static IP
  annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: MC_ZPUE-DNT-rg_az_k8s_1_northeurope
      service.beta.kubernetes.io/azure-pip-name: influx_public_ip
## Here annotations can be added to the openvpn pod
# podAnnotations:
#   backup.ark.heptio.com/backup-volumes: certs
podAnnotations: {}

# Add privileged init container to enable IPv4 forwarding
ipForwardInitContainer: true

resources:
  limits:
    cpu: 300m
    memory: 128Mi
  requests:
    cpu: 300m
    memory: 128Mi

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 20
  successThreshold: 2

persistence:
  enabled: true
  # subPath: pki
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:

  ## openvpn data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  useCustomStorageClass: true
  storageClass: openvpn-managed-premium-retain
  accessMode: ReadWriteOnce
  size: 100Mi
  provisioner: disk.csi.azure.com
  skuName: Premium_LRS
openvpn:
  # Network allocated for openvpn clients (default: 10.240.0.0).
  OVPN_NETWORK: 10.2.0.0
  # Network subnet allocated for openvpn client (default: 255.255.0.0).
  OVPN_SUBNET: 255.255.0.0
  # Protocol used by openvpn tcp or udp (default: udp).
  OVPN_PROTO: tcp
  # CERT expiration
  OVPN_CERT_EXPIRATION: 36500
  # Kubernetes pod network (optional).
  # OVPN_K8S_POD_NETWORK: "100.66.0.0"
  OVPN_K8S_POD_NETWORK: "null"
  # Kubernetes pod network subnet (optional).
  # OVPN_K8S_POD_SUBNET: "255.255.128.0"
  OVPN_K8S_POD_SUBNET: "null"
  # Kubernetes service network (optional).
  # Define openvpn.OVPN_K8S_SVC_NETWORK and openvpn.OVPN_K8S_SVC_SUBNET if it's needed to create a separate route to Kubernates service subnet
  # OVPN_K8S_SVC_NETWORK: "100.76.0.0"
  # Kubernetes service network subnet (optional).
  # OVPN_K8S_SVC_SUBNET: "255.255.192.0"
  # Set default route which openvpn figures basing on network routes inside openvpn pod
  DEFAULT_ROUTE_ENABLED: true
  # Server certificate data
  # keystoreSecret:
  # secret with openvpn certificates. If specified, certificates are taken from the secret
  # create secret with such command:
  #    kubectl create secret generic openvpn-keystore-secret --from-file=./server.key --from-file=./ca.crt --from-file=./server.crt --from-file=./dh.pem [--from-file=./crl.pem]  [--from-file=./ta.key]
  # Push a `dhcp-option DOMAIN` config
  dhcpOptionDomain: true
  # Redirect all client traffic through VPN
  redirectGateway: false
  # Use/generate certificate revocation list
  useCrl: true
  # Use/generate a ta.key (https://openvpn.net/community-resources/hardening-openvpn-security/)
  taKey: true
  # Override default cipher
  cipher: AES-256-GCM
  # Lines appended to the end of the server configuration file
  #  max-clients 100
  serverConf: |
    # duplicate-cn
    max-clients 100000

  management:
    enabled: true
    port: 5555

  istio:
    enabled: false
    proxy:
      port: 15001
  iptablesExtra: []
  # - -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
  # - -A FORWARD -m conntrack --ctstate NEW -d 10.240.0.0/255.255.0.0 -j ACCEPT
  # - -A FORWARD -j REJECT

  # Enable CCD support
  ccd:
    enabled: true
    config: {}
    # johndoe: "ifconfig-push 10.240.100.10 10.240.100.11"
    # janedoe: "ifconfig-push 10.240.100.20 10.240.100.21"

nodeSelector: {}
tolerations: []
